### ISSUE TITLE
GeoPackage NSG 2.0 Support?

### ISSUE THREAD

**Issue by geospatialmapmashup** [ngageoint/mage-android-sdk#15]
Does MAGE Android SDK  been updated to support the NGA's NSG GeoPackage Tiling Profile Specification?  (NSG) GeoPackage Encoding Standard 2.0
Interoperability Standard
(2016-09-14)

**Comment by bosborn** [comment]
NSG is fully supported except for NGA CRS authored WKT coordinate system values.

Please see ngageoint/GeoPackage#4
