### ISSUE TITLE
Cordova plugin

### ISSUE THREAD

**Issue by HarelM** [ngageoint/mage-android-sdk#20]
Hi,

We are looking into offline solution for our cordova based application.
Looking at this project and the problem it comes to solve seems very similar to our needs.
I was wondering if there's a cordova plugin that was written on top of the two (android and iOS) sdks to facilitate for a single UI development for both platforms.
You can checkout our project at https://israelhiking.osm.org.il/
Or our github project:
Https://www.github.com/israelhikingmap/site/

**Comment by newmanw** [comment]
Sorry, I am not currently aware of a cordova plugin that would suit your needs.  MAGE is based on a RESTful API, you should be able to make http(s) requests from your cordova application if you have setup your own MAGE server.

**Comment by HarelM** [comment]
What I'm proposing, and since I still don't fully understand this project it might be an invalid proposal, is to create a cordova plug-in as part of this project to wrap the native capabilities in a plugin so that writing a client can be done once using javascript etc.
Since this project aims to facilitate for events where you have to operate in offline mode I guess, but I haven't fully dived into the code yet, that there are native code to store stuff in a database that is later synchronized with a server. I would like to write similar code but it would be better for me if I could leverage the code you already wrote and only write the cordova plug-in that wraps it.
I think it can be a good addition to this project, but I might be wrong.
I would be happy to better understand how this project works and if we can work together on something like that plugin...
